### ISSUE TITLE
getting Uncaught DOMException

### ISSUE THREAD

**Issue by ghost** [benzap/flyer.js#5]
Hi,

I am getting these errors:

Uncaught DOMException (Chrome), Permission denied to access property "flyer_WindowReferences" (Firefox), Blocked a frame with origin... (Safari)

Markup hosted on Domain A:

```
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />
        <title></title>

        <script>
            window.onload = function () {
                flyer.subscribe({
                    channel: "test",
                    topic: "some.topic",
                    callback: function () {
                        console.log("event received!!!");
                    }
                });
            };
        </script>

        <script src="flyer.js"></script>

    </head>
    <body>
        <iframe src="http://some.other.host.com:80/flyer_inside.html"></iframe>
    </body>
</html>
```

Markup hosted on Domain B (http://some.other.host.com:80/flyer_inside.html):

```
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />
        <title></title>

        <script>
            var clickHandler = function() {
                flyer.broadcast({
                    channel: "test",
                    topic: "some.topic",
                    data: {}
                });
                console.log("flyer event broadcast!");
            };
        </script>
        <script src="flyer.js"></script>

    </head>
    <body>
        <button onclick="clickHandler()">click here to broadcast flyer event</button>
    </body>
</html>
```

Error seems to come from line 28699 in flyer.js, just setting _or__3638__auto___ to undefined seems to hotfix the problem.

BR, Matthias

**Comment by benzap** [comment]
Hey Matthias,

Looking over the issue, I wonder if it has something to do with tighter restrictions on cross-origin messaging.

By default, the postMessage that i'm performing on each frame is assigned to *all targets* and this is usually frowned upon or not recommended to use for potential security reasons.

The code snippet you mentioned within the clojurescript codebase is here: https://github.com/benzap/flyer.js/blob/master/src-cljs/flyer/storage.cljs#L17

By setting this to undefined, you prevent the frames from being sent a message. I've had issues with this in the past with IE8, and i'm not sure if it's a problem with the pages not being loaded fast enough. However, it might be an issue with the introduction of tighter restrictions when posting messages between different domains.

A possible solution would be to be explicit with your origin when you're sending a broadcast.

So you would change this in domain B:

`                flyer.broadcast({
                    channel: "test",
                    topic: "some.topic",
                    data: {}
                });`

to include the target domain:

`                flyer.broadcast({
                    channel: "test",
                    topic: "some.topic",
                    data: {},
                    target: "http://domain-a.somehost.com"
                });`

Hope this helps, and thanks for the feedback!

Ben
