### ISSUE TITLE
Error when opening new tab via link onto a page with flyer.js

### ISSUE THREAD

**Issue by Arany** [benzap/flyer.js#6]
Steps to Reproduce
1) Create 2 html Pages:

page_with_flyer.html

    <script src="flyer.min.js"></script>

page_with_link.html

    <a href="page_with_flyer.html" target="_blank">

2) Open page_with_link.html and click on the link

->
On the newly opened tab, the Browser throws an Exception (tested with firefox and chrome):
Error: Permission denied to access property "flyer_WindowReferences"

This now prevents other javascript to be executed (in a minified file of all javascript on the page)

I tried adding try/catches into the storage.cljs file, which makes it not BREAK the whole javascript, but flyer.js does not work afterwards, when opening via a link.

This is what i tried:

    (defn init-window-refs 
      "Initializes our window references"
      []
      (try
          (when (nil? (get-window-refs))
              (aset storage window-list-key (set nil)))
          (catch :default e
                (console.log e)
                nil)))
    
    (defn get-window-refs 
      "Returns the window references, or an empty set"
      []
      (try
        (or
           (aget storage window-list-key)
           nil)
        (catch :default e
          (console.log e)
          nil)))
    
    
    (defn insert-window-ref! [window]
      (init-window-refs)
      (try
          (aset storage window-list-key
                  (conj (get-window-refs) window))
          (catch :default e
                (console.log e)
                nil)))
    
    (defn remove-window-ref! [window]
      (try
            (aset storage window-list-key
                    (disj (get-window-refs) window))
            (catch :default e
                  (console.log e)
                  nil

**Comment by benzap** [comment]
Hey @Arany,

Thanks for info! I might look into improving flyer.js and rewrite portions of it. This will likely come as a flyerjs 2.0 release.

The issue you're seeing might have something to do with stricter guidelines in the later versions of chrome and firefox when accessing iframes or external windows. It's failing to grab the window handles in certain situations. This might explain why you're seeing a 'permission denied'

As for just simply avoiding the window reference, i'll look into implementing soft warnings when things don't work out.

Cheers,

Ben
