### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by martinklepsch** [benzap/flyer.js#7]
Hey! I just stumbled over flyer.js because a documentation service I’m working on picked up the latest release: https://cljdoc.xyz/d/flyer/flyer/1.1.1

It seems like a cool project and since you’re targeting JS as well there’s probably some interesting optimizations to reduce the bundle size. I previously tried some [similar minification](https://github.com/martinklepsch/martinklepsch.com/blob/master/src/com/martinklepsch/dyn.cljs) — waaay less code admittedly — but I learned a few things that might be interesting for you as well:

- [`str`](https://github.com/benzap/flyer.js/search?q=str&unscoped_q=str) brings in a lot of stuff. In the linked example using `str` instead of `goog/buildString` adds 88K to the `:advanced` build. (Note that `clj->js` uses `str` under the hood so YMMV.)
- If I remember correctly `case` is significantly leaner than [`cond`](https://github.com/benzap/flyer.js/search?q=cond&unscoped_q=cond) — obviously not the same thing though so can't always replace `cond`. 

I hope this is useful to you or at the very least interesting! 🙂 Cheers!

**Comment by benzap** [comment]
Hey, thanks for the heads up!

It's been a while since I really touched the code, so i'm thankful for these tidbits. I'm looking into cleaning up the code a bit more, so i'll definitely look into incorporating some of these changes, and get the bundle size down.

**Comment by benzap** [comment]
So I cleaned up the code and moved a few things around to get the size down, but the bundle size didn't appear to go down that much. I removed all of the cond statements, and replaced them with case and nested ifs. I removed clj->js, and made handcoded js/Object constructors. Saved 5kbs 😠 

I think the problem area might be the flyer.window/gen-window-options function. I removed all of the `str` functions, and used clojure.string/join to see if that would reduce the size. This didn't seem to have much of an effect (127kb -> 122kb).

I'm open to any further suggestions, but it seems like it's stuck at 122kb for now.

**Comment by martinklepsch** [comment]
You could try `goog.string/buildString` instead of `clojure.string/join` but not sure if that will make a difference.

**Comment by benzap** [comment]
I tried using goog.string/buildString

`(require '[goog.string :as gstr])`

`(defn gen-window-options
  [& options]
  (as-> options $
   (partition 2 $)
   (map (fn [[x y]] (gstr/buildString (name x) "=" y ", ")) $)
   (reduce #(gstr/buildString %1 %2) $)
   (.substr $ 0 (- (.-length $) 2))))`

This increased the size  by 2kb, I did a bit of grepping, and I think the culprit is https://github.com/benzap/flyer.js/blob/master/src-cljs/flyer/messaging.cljs#L31

I don't think there's anything around this particular clj->js function, so this might be considered the best size I can get for now.

**Comment by martinklepsch** [comment]
Alright, sorry for leading you down this rabbit hole  😇  Guess we learned something 😅
